### ISSUE TITLE
Nice mention of lodash-fp.

### ISSUE THREAD

**Issue by jdalton** [stoeffel/underscore.string.fp#1]
lodash v3 has a flavor with more functional goodness, [lodash-fp](https://www.npmjs.com/package/lodash-fp). It would be rad if it had a mention in the readme too since it's in the same vein as Underscore. You can read more on it [here](https://github.com/lodash/lodash/releases/tag/3.0.0) too.

If you'd like a PR I can do that too but I figured it's mostly wording which is really your preference.

**Comment by jdalton** [comment]
If you'd like a PR I can do that too but I figured it's mostly wording which is really your preference.

**Comment by stoeffel** [comment]
Yes, sure. I will add it to the readme and all the descriptions.
Btw `lodash-fp` looks really nice.
